const LogisticData = [
  {
    shipmentId: "357",
    productName: "Widget A",
    quantity: 100,
    destination: "City X",
    status: "In Transit",
    price: 150,
  },
  {
    shipmentId: "234",
    productName: "Gadget C",
    quantity: 75,
    destination: "City Z",
    status: "In Transit",
    price: 120,
  },
  {
    shipmentId: "457",
    productName: "Device D",
    quantity: 200,
    destination: "City Y",
    status: "Returned",
    price: 160,
  },
  {
    shipmentId: "654",
    productName: "Accessory E",
    quantity: 10,
    destination: "City X",
    status: "Delivered",
    price: 50,
  },
  {
    shipmentId: "346",
    productName: "Gizmo F",
    quantity: 130,
    destination: "City Z",
    status: "In Transit",
    price: 90,
  },
  {
    shipmentId: "288",
    productName: "Widget A",
    quantity: 70,
    destination: "City Y",
    status: "In Transit",
    price: 130,
  },
  {
    shipmentId: "237",
    productName: "Gadget C",
    quantity: 90,
    destination: "City X",
    status: "Delivered",
    price: 110,
  },
  {
    shipmentId: "325",
    productName: "Device D",
    quantity: 120,
    destination: "City Z",
    status: "In Transit",
    price: 160,
  },
  {
    shipmentId: "343",
    productName: "Gadget C",
    quantity: 110,
    destination: "City Z",
    status: "In Transit",
    price: 140,
  },
  {
    shipmentId: "974",
    productName: "Gizmo F",
    quantity: 70,
    destination: "City Z",
    status: "Returned",
    price: 100,
  },
  {
    shipmentId: "455",
    productName: "Widget A",
    quantity: 75,
    destination: "City Y",
    status: "In Transit",
    price: 110,
  },
  {
    shipmentId: "462",
    productName: "Gadget C",
    quantity: 60,
    destination: "City X",
    status: "In Transit",
    price: 90,
  },
  {
    shipmentId: "568",
    productName: "Device D",
    quantity: 100,
    destination: "City Z",
    status: "Delivered",
    price: 140,
  },
];

export default LogisticData;